<?php

use Illuminate\Database\Seeder;

class DataTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('configuraciones')->insert([
            ['id' => '1', 'accion' => 'web_nombre', 'valor' => 'Consensus'],
            ['id' => '2', 'accion' => 'web_logo', 'valor' => 'logo.jpg'],
            ['id' => '3', 'accion' => 'notificacion_dias', 'valor' => '7']
        ]);

        DB::table('money')->insert([
            ['id' => '1', 'titulo' => 'Dólar', 'valor' => '3.29330', 'simbolo' => 'US$', 'abrev' => 'USD', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'Euro', 'valor' => '3.72860', 'simbolo' => '€', 'abrev' => 'EUR', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'Nuevo Sol', 'valor' => '1', 'simbolo' => 'S/.', 'abrev' => 'PEN', 'estado' => '1'],
        ]);

        DB::table('payment_methods')->insert([
            ['id' => '1', 'titulo' => 'cheque', 'estado' => '0'],
            ['id' => '2', 'titulo' => 'CONTADO AL FINAL ', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'CONTADO AL INICIO ', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'DOS PARTES ', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'PLAZO CON FECHAS ESTABLECIDAS ', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'ETAPAS DEL PROCESO', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'SEMANAL', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'MENSUAL', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'POR PORCENTAJE', 'estado' => '1']
        ]);

        DB::table('tariffs')->insert([
            ['id' => '1', 'titulo' => 'EVENTUALES', 'abrev' => 'EV', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'HONORARIO FIJO', 'abrev' => 'HF', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'HORA FIJA', 'abrev' => 'OF', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'HORA POR ABOGADO', 'abrev' => 'HA', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'RETAINER FM', 'abrev' => 'FM', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'RETAINER TH', 'abrev' => 'TH', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'RETAINER TM', 'abrev' => 'TM', 'estado' => '1']
        ]);

        DB::table('services')->insert([
            ['id' => '1', 'titulo' => 'ACTA ESPECIAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'ACTA SIMPLE', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'AUMENTO DE CAPITAL (ACTA Y MINUTA)', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'MODIFICACION DE ESTATUTOS (ACTA Y MINUTA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'CANCELACION DE HIPOTECA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'CARTA ESPECIAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'CARTA SIMPLE', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'CLAUSULA ADICIONAL ESPECIAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'CLAUSULA ADICIONAL SIMPLE', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '10', 'titulo' => 'CONSTITUCION DE ASOCIACION (ACTA Y MINUT', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '11', 'titulo' => 'CONSTITUCION DE SOCIEDAD', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '12', 'titulo' => 'CONSTITUCION DE EMPRESA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '13', 'titulo' => 'CONSULTA LEGAL SIMPLE', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '14', 'titulo' => 'CONSULTA LEGAL ESPECIAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '15', 'titulo' => 'CONTRATO DE ARRENDAMIENTO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '16', 'titulo' => 'CONTRATO PRIVADO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '17', 'titulo' => 'CONVENIO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '18', 'titulo' => 'DECLARACION JURADA ESPECIAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '19', 'titulo' => 'DECLARACION JURADA SIMPLE', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '20', 'titulo' => 'RECURSOS PROCESALES', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '21', 'titulo' => 'ESTUDIO DE TITULO INFORME POR ESCRITO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '22', 'titulo' => 'ESTUDIO DE TITULO INFORME ORAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '23', 'titulo' => 'ESTUDIO DE TITULO INFORME ESCRITO Y NUEV', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '24', 'titulo' => 'INTERVENCION LEGAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '25', 'titulo' => 'MINUTA DE ACLARACION', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '26', 'titulo' => 'MINUTA DE ANTICIPO DE LEGITIMA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '27', 'titulo' => 'MINUTA DE COMPRA VENTA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '28', 'titulo' => 'MINUTA DE SEPARACION DE PATRIMONIOS', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '29', 'titulo' => 'PRESTAMO HIPOTECARIO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '30', 'titulo' => 'PRESTAMO CON GARANTIA MOBILIARIA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '31', 'titulo' => 'SOLICITUD ADMINISTRATIVA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '32', 'titulo' => 'MINUTA DE DIVISION, PARTICION, ADJUDICAC', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '33', 'titulo' => 'SUBSANACION DE OBSERVACION', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '34', 'titulo' => 'TOMA DE FIRMA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '35', 'titulo' => 'TRAMITE ADMINISTRATIVO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '36', 'titulo' => 'TRAMITE BUSQUEDA REGISTRAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '37', 'titulo' => 'TRAMITE DE INSCRIPCION REGISTRAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '38', 'titulo' => 'DOCUMENTO REGISTRAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '39', 'titulo' => 'TRAMITE PROVINCIA BANCOS', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '40', 'titulo' => 'TRAMITE PROVINCIA OTROS', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '41', 'titulo' => 'ESCRITO DE DEMANDA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '42', 'titulo' => 'ESCRITO CONTESTACION DE DEMANDA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '43', 'titulo' => 'RECURSO DE APELACION', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '44', 'titulo' => 'RECURSO DE CASACION', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '45', 'titulo' => 'SOLICITUD ASUNTOS NO CONTENCIOSOS', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '46', 'titulo' => 'PROCESO JUDICIAL CONTENCIOSO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '47', 'titulo' => 'PROCESO JUDICIAL NO CONTENCIOSO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '48', 'titulo' => 'CARTA PODER', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '49', 'titulo' => 'INFORME ORAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '50', 'titulo' => 'INFORME ESCRITO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '51', 'titulo' => 'TRAMITE PROCESAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '52', 'titulo' => 'TRAMITE NOTARIAL', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '53', 'titulo' => 'PODER FUERA DE REGISTRO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '54', 'titulo' => 'PODER POR ESCRITURA PUBLICA', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '55', 'titulo' => 'PODER PARA EL EXTRANJERO', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '56', 'titulo' => 'SOLICITUD ANTE REGISTROS', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '57', 'titulo' => 'ESCRITO DE APELACION, RECONSIDERACION, R', 'dias_ejecucion' => '0', 'estado' => '1'],
            ['id' => '58', 'titulo' => 'CONTRATO DE ARRAS PROMESA DE VENTA', 'dias_ejecucion' => '0', 'estado' => '1']
        ]);

        DB::table('instances')->insert([
            ['id' => '1', 'titulo' => 'PRIMERA INSTANCIA: JUZGADO DE PAZ', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'PRIMERA INSTANCIA: JUZGADO CIVIL', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'SEGUNDA INSTANCIA: JUZGADO CIVIL', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'SEGUNDA INSTANCIA: CORTE SUPERIOR', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'CASACION', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'CORTE SUPREMA', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'PRIMERA INSTANCIA: SUBGERENCIA', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'SEGUNDA INSTANCIA: GERENCIA', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'PRIMERA INSTANCIA: REGISTRADOR', 'estado' => '1'],
            ['id' => '10', 'titulo' => 'SEGUNDA INSTANCIA:TRIBUNAL REGISTRA', 'estado' => '1']
        ]);

        DB::table('matters')->insert([
            ['id' => '1', 'titulo' => 'CIVIL', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'PENAL', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'CONTENCIOSO ADMINISTRATIVO', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'LABORAL', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'CONSTITUCIONAL', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'PREVISIONAL', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'CONCILIACION', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'ARBITRAJE', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'MUNICIPAL', 'estado' => '1'],
            ['id' => '10', 'titulo' => 'REGISTRAL', 'estado' => '1'],
            ['id' => '11', 'titulo' => 'TRIBUTARIO MUNICIPAL', 'estado' => '1'],
            ['id' => '12', 'titulo' => 'NOTARIAL', 'estado' => '1'],
            ['id' => '13', 'titulo' => 'CONTRATOS', 'estado' => '1'],
            ['id' => '14', 'titulo' => 'SUCESIONES', 'estado' => '1'],
            ['id' => '15', 'titulo' => 'ADMINISTRATIVO', 'estado' => '1'],
            ['id' => '16', 'titulo' => 'SOCIETARIO', 'estado' => '1'],
            ['id' => '17', 'titulo' => 'SIGNOS DISTINTIVOS', 'estado' => '1'],
            ['id' => '18', 'titulo' => 'TRIBUTARIO', 'estado' => '1'],
            ['id' => '19', 'titulo' => 'PERSONAS JURIDICAS', 'estado' => '1'],
            ['id' => '20', 'titulo' => 'FAMILIA TUTELAR', 'estado' => '1'],
            ['id' => '21', 'titulo' => 'PROTECCION AL CONSUMIDOR', 'estado' => '1'],
            ['id' => '22', 'titulo' => 'PROTESTO', 'estado' => '1'],
            ['id' => '23', 'titulo' => 'SINIESTRO PERDIDA TOTAL', 'estado' => '1'],
            ['id' => '24', 'titulo' => 'SINIESTRO ROBO TOTAL', 'estado' => '1'],
            ['id' => '25', 'titulo' => 'MINERO', 'estado' => '1'],
            ['id' => '26', 'titulo' => 'DERECHO INTERNACIONAL PRIVADO', 'estado' => '1'],
            ['id' => '27', 'titulo' => 'PERSONAS', 'estado' => '1']
        ]);

        DB::table('entities')->insert([
            ['id' => '1','titulo' => 'PODER JUDICIAL','area' => 'JUZGADO','funcionario' => 'JUEZ','otro' => 'ESPECIALISTA LEGAL','estado' => '1'],
            ['id' => '2','titulo' => 'PODER JUDICIAL','area' => 'JUZGADO','funcionario' => 'JUEZ','otro' => 'ARCHIVO','estado' => '0'],
            ['id' => '3','titulo' => 'PODER JUDICIAL','area' => 'SALA SUPERIOR','funcionario' => 'VOCALES SUPERIORES','otro' => 'RELATOR','estado' => '0'],
            ['id' => '4','titulo' => 'PODER JUDICIAL','area' => 'SALA SUPERIOR','funcionario' => 'VOCALES SUPERIORES','otro' => 'ESCRIBANIA','estado' => '0'],
            ['id' => '5','titulo' => 'MINISTERIO PUBLICO','area' => 'FISCALIA','funcionario' => 'FISCAL','otro' => 'ASISTENTE DE FUNCION FISCAL','estado' => '1'],
            ['id' => '6','titulo' => 'MUNICIPALIDAD ','area' => 'MESA DE PARTES','funcionario' => 'RECEPTOR','otro' => 'ORIENTADOR','estado' => '1'],
            ['id' => '7','titulo' => 'MUNICIPALIDAD ','area' => 'GERENCIA DE RENTAS','funcionario' => 'GERENTE','otro' => 'SUBGERENTE','estado' => '0'],
            ['id' => '8','titulo' => 'MUNICIPALIDAD ','area' => 'GERENCIA DE RENTAS','funcionario' => 'GERENTE ','otro' => 'RECEPTOR','estado' => '0'],
            ['id' => '9','titulo' => 'MUNICIPALIDAD ','area' => 'CATASTRO','funcionario' => 'GERENTE','otro' => 'SUBGERENTE','estado' => '0'],
            ['id' => '10','titulo' => 'MUNICIPALIDAD ','area' => 'CATASTRO','funcionario' => 'GERENTE','otro' => 'SUBGERENTE','estado' => '0'],
            ['id' => '11','titulo' => 'MUNICIPALIDAD','area' => 'CATASTRO','funcionario' => 'GERENTE','otro' => 'RECEPTOR','estado' => '0'],
            ['id' => '12','titulo' => 'MUNICIPALIDAD','area' => 'FISCALIZACION','funcionario' => 'FISCALIZADOR','otro' => 'INSPECTOR','estado' => '0'],
            ['id' => '13','titulo' => 'MUNICIPALIDAD ','area' => 'FISCALIZACION','funcionario' => 'FISCALIZADOR','otro' => 'NOTIFICADOR','estado' => '0'],
            ['id' => '14','titulo' => 'MUNICIPALIDAD','area' => 'OBRAS PRIVADAS','funcionario' => 'GERENTE','otro' => 'SUBGERENTE','estado' => '0'],
            ['id' => '15','titulo' => 'MUNICIPALIDAD','area' => 'OBRAS PRIVADAS','funcionario' => 'GERENTE ','otro' => 'TECNICOS','estado' => '0'],
            ['id' => '16','titulo' => 'MUNICIPALIDAD','area' => 'SECRETARIA GENERAL','funcionario' => 'SECRETARIO GENERAL','otro' => 'ARCHIVO','estado' => '0'],
            ['id' => '17','titulo' => 'MUNICIPALIDAD ','area' => 'ALCALDIA','funcionario' => 'ALCALDE','otro' => 'REGIDOR','estado' => '0'],
            ['id' => '18','titulo' => 'MUNICIPALIDAD ','area' => 'ALCALDIA','funcionario' => 'ALCALDE','otro' => 'CONSEJERO','estado' => '0'],
            ['id' => '19','titulo' => 'NOTARIA','area' => 'CONTRATOS','funcionario' => 'ABOGADO','otro' => 'NOTARIO','estado' => '1'],
            ['id' => '20','titulo' => 'NOTARIO','area' => 'LEGALIZACIONES','funcionario' => 'ENCARGADO','otro' => 'PROCURADOR','estado' => '1'],
            ['id' => '21','titulo' => 'SUNARP','area' => 'MESA DE PARTES','funcionario' => 'RECEPTOR','otro' => 'CAJERO','estado' => '1'],
            ['id' => '22','titulo' => 'SUNARP','area' => 'DEFENSORIA DEL USUARIO','funcionario' => 'ABOGADO','otro' => '','estado' => '0'],
            ['id' => '23','titulo' => 'SUNARP','area' => 'PUBLICIDAD REGISTRAL','funcionario' => 'CERTIFICADOR','otro' => '','estado' => '0'],
            ['id' => '24','titulo' => 'SUNARP','area' => 'GERENCIA DE PROPIEDAD INMUEBLE','funcionario' => 'REGISTRADOR','otro' => 'ASISTENTE','estado' => '0'],
            ['id' => '25','titulo' => 'SUNARP','area' => 'TRIBUNAL REGISTRAL','funcionario' => 'VOCAL','otro' => 'SECRETARIA','estado' => '0'],
            ['id' => '26','titulo' => 'SUNARP','area' => 'TRIBUNAL REGISTRAL','funcionario' => 'PRESIDENTE','otro' => 'SECRETARIA','estado' => '0'],
            ['id' => '27','titulo' => 'SUNAT','area' => 'MESA DE PARTES','funcionario' => 'ORIENTADOR','otro' => 'RECEPTOR','estado' => '1'],
            ['id' => '28','titulo' => 'SUNAT','area' => 'MESA DE PARTES','funcionario' => 'SUPERINTENDETE','otro' => 'FISCALIZADOR','estado' => '0'],
            ['id' => '29','titulo' => 'SAT','area' => 'GERENCIA','funcionario' => 'GERENTE','otro' => 'SUBGERENTE','estado' => '1'],
            ['id' => '30','titulo' => 'SUNARP','area' => 'GERENCIA DE PERSONAS JURIDICAS','funcionario' => 'REGISTRADOR','otro' => 'ASISTENTE','estado' => '0'],
            ['id' => '31','titulo' => 'SUNARP','area' => 'GERENCIA DE MANDATOS Y PODERES','funcionario' => 'REGISTRADOR','otro' => 'ASISTENTE','estado' => '0'],
            ['id' => '32','titulo' => 'NOTARIA','area' => 'VEHICULAR','funcionario' => 'ABOGADO','otro' => 'ASISTENTE','estado' => '0'],
            ['id' => '33','titulo' => 'NOTARIA ','area' => 'PROTESTOS','funcionario' => 'NOTARIO','otro' => 'ASISTENTE','estado' => '0'],
            ['id' => '34','titulo' => 'SAT','area' => 'GERENCIA','funcionario' => 'ESPECIALISTA','otro' => 'TECNICO','estado' => '0'],
            ['id' => '35','titulo' => 'MUNICIPALIDAD','area' => 'GERENCIA','funcionario' => 'EJECUTOR COACTIVO','otro' => 'TECNICO','estado' => '0']
        ]);

        DB::table('areas')->insert([
            ['id' => '1', 'titulo' => 'ADMINISTRACION', 'email' => 'rpiera@consensus.com.pe', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'PROCESAL ESPECIAL', 'email' => 'agonzales@consensus.com.pe', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'INMOBILIARIO ESPECIAL', 'email' => 'osolis@consensus.com.pe', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'INMOBILIARIO', 'email' => 'inmobiliaria1@consensus.com.pe', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'CORPORATIVO', 'email' => 'corporativo1@consensus.com.pe', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'PROCESAL', 'email' => 'judicial2@consensus.com.pe', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'KARDEX', 'email' => 'asistentelegal1@consensus.com.pe', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'VEHICULAR', 'email' => 'vehicular@consensus.com.pe', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'PROCURACIÃ“N', 'email' => 'jfigueroa@consensus.com.pe', 'estado' => '1'],
            ['id' => '10', 'titulo' => 'LEGAL', 'email' => 'mgonzales@consensus.com.pe', 'estado' => '1'],
            ['id' => '11', 'titulo' => 'GERENCIA', 'email' => 'fflorez@consensus.com.pe', 'estado' => '1'],
            ['id' => '12', 'titulo' => 'PERSONAS', 'email' => 'CORPORATIVO1@CONSENSUS.COM.PE', 'estado' => '1'],
            ['id' => '13', 'titulo' => 'PAGARES', 'email' => 'vehicular@consensus.com.pe', 'estado' => '1']
        ]);

        DB::table('ubicaciones')->insert([
            ['id' => '1', 'titulo' => 'ESPECIALISTA LEGAL', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'ARCHIVO DEL JUZGADO', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'DESPACHO DEL JUEZ', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'ARCHIVO DEFINITIVO', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'CALIFICACION ', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'MESA DE PARTES', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'DESPACHO DEL REGISTRADOR ', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'CATASTRO', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'SECRETARIA GENERAL', 'estado' => '1'],
            ['id' => '10', 'titulo' => 'ARCHIVO', 'estado' => '1'],
            ['id' => '11', 'titulo' => 'NOTIFICACIONES', 'estado' => '1'],
            ['id' => '12', 'titulo' => 'TRAMITE DOCUMENTARIO', 'estado' => '1'],
            ['id' => '13', 'titulo' => 'DESPACHO DEL NOTARIO', 'estado' => '1'],
            ['id' => '14', 'titulo' => 'RENTAS', 'estado' => '1']
        ]);

        DB::table('states')->insert([
            ['id' => '1', 'titulo' => 'EN PROCESO', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'EN APELACION', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'EN CALIFICACION', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'ADMITIDA', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'IMPROCEDENTE', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'SENTENCIADO', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'CONSENTIDO', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'EJECUTADO', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'ARCHIVADO', 'estado' => '1'],
            ['id' => '10', 'titulo' => 'PRESENTADO', 'estado' => '1'],
            ['id' => '11', 'titulo' => 'OBSERVADO', 'estado' => '1'],
            ['id' => '12', 'titulo' => 'SUBSANADO', 'estado' => '1'],
            ['id' => '13', 'titulo' => 'RESUELTO - PROCEDENTE', 'estado' => '1'],
            ['id' => '14', 'titulo' => 'RESUELTO - IMPROCEDENTE', 'estado' => '1'],
            ['id' => '15', 'titulo' => 'LIQUIDADO', 'estado' => '1'],
            ['id' => '16', 'titulo' => 'TACHADO', 'estado' => '1'],
            ['id' => '17', 'titulo' => 'SUSPENDIDO', 'estado' => '1'],
            ['id' => '18', 'titulo' => 'INSCRITO', 'estado' => '1'],
            ['id' => '19', 'titulo' => 'CONCLUIDO', 'estado' => '1'],
            ['id' => '20', 'titulo' => 'PENDIENTE DE RESPUESTA', 'estado' => '1'],
            ['id' => '21', 'titulo' => 'REINGRESADO', 'estado' => '1'],
            ['id' => '22', 'titulo' => 'CASO CERRADO', 'estado' => '1'],
            ['id' => '23', 'titulo' => 'DESPACHADO', 'estado' => '1'],
            ['id' => '24', 'titulo' => 'EN TRAMITE', 'estado' => '1'],
            ['id' => '25', 'titulo' => 'REVISION', 'estado' => '1']
        ]);

        DB::table('interveners')->insert([
            ['id' => '1', 'titulo' => 'DEMANDANTE', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'DEMANDADO', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'EJECUTANTE', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'EJECUTADO', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'TERCERO', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'TESTIGO', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'PERITO', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'COMPRADOR', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'POSEEDOR', 'estado' => '1'],
            ['id' => '10', 'titulo' => 'VENDEDOR', 'estado' => '1'],
            ['id' => '11', 'titulo' => 'DONANTE', 'estado' => '1'],
            ['id' => '12', 'titulo' => 'DONATARIO', 'estado' => '1'],
            ['id' => '13', 'titulo' => 'ARRENDADOR', 'estado' => '1'],
            ['id' => '14', 'titulo' => 'ARRENDATARIO', 'estado' => '1'],
            ['id' => '15', 'titulo' => 'CEDENTE', 'estado' => '1'],
            ['id' => '16', 'titulo' => 'CESIONARIO', 'estado' => '1'],
            ['id' => '17', 'titulo' => 'CEDIDO', 'estado' => '1'],
            ['id' => '18', 'titulo' => 'ANTICIPADO', 'estado' => '1'],
            ['id' => '19', 'titulo' => 'ANTICIPANTE', 'estado' => '1'],
            ['id' => '20', 'titulo' => 'CAUSANTE', 'estado' => '1'],
            ['id' => '21', 'titulo' => 'HEREDERO', 'estado' => '1'],
            ['id' => '22', 'titulo' => 'LEGATARIO', 'estado' => '1'],
            ['id' => '23', 'titulo' => 'HIPOTECANTE', 'estado' => '1'],
            ['id' => '24', 'titulo' => 'ACREEDOR', 'estado' => '1'],
            ['id' => '25', 'titulo' => 'DEUDOR', 'estado' => '1'],
            ['id' => '26', 'titulo' => 'FIADOR', 'estado' => '1'],
            ['id' => '27', 'titulo' => 'GARANTE', 'estado' => '1'],
            ['id' => '28', 'titulo' => 'INTERVINIENTE', 'estado' => '1'],
            ['id' => '29', 'titulo' => 'CURADOR', 'estado' => '1'],
            ['id' => '30', 'titulo' => 'APODERADO', 'estado' => '1'],
            ['id' => '31', 'titulo' => 'REPRESENTANTE', 'estado' => '1'],
            ['id' => '32', 'titulo' => 'TUTOR', 'estado' => '1'],
            ['id' => '33', 'titulo' => 'PODERDANTE', 'estado' => '1'],
            ['id' => '34', 'titulo' => 'CONTRIBUYENTE', 'estado' => '1'],
            ['id' => '35', 'titulo' => 'ADMINISTRADO', 'estado' => '1'],
            ['id' => '36', 'titulo' => 'USUARIO', 'estado' => '1'],
            ['id' => '37', 'titulo' => 'PRESENTANTE', 'estado' => '1'],
            ['id' => '38', 'titulo' => 'FISCALIZADO', 'estado' => '1'],
            ['id' => '39', 'titulo' => 'OTORGANTE', 'estado' => '1'],
            ['id' => '40', 'titulo' => 'EMPRESA', 'estado' => '1'],
            ['id' => '41', 'titulo' => 'REPRESENTANTE LEGAL', 'estado' => '1'],
            ['id' => '42', 'titulo' => 'TESTADOR', 'estado' => '1'],
            ['id' => '43', 'titulo' => 'ASEGURADO', 'estado' => '1'],
            ['id' => '44', 'titulo' => 'USUFRUCTUANTE', 'estado' => '1'],
            ['id' => '45', 'titulo' => 'BENEFICIARIO', 'estado' => '1'],
            ['id' => '46', 'titulo' => 'RESPONSABLE TRIBUTARIO', 'estado' => '1'],
            ['id' => '47', 'titulo' => 'SOCIO', 'estado' => '1'],
            ['id' => '48', 'titulo' => 'ACCIONISTA', 'estado' => '1'],
            ['id' => '49', 'titulo' => 'PARTICIPACIONISTA', 'estado' => '1'],
            ['id' => '50', 'titulo' => 'TITULAR', 'estado' => '1'],
            ['id' => '51', 'titulo' => 'ALBACEA', 'estado' => '1'],
            ['id' => '52', 'titulo' => 'TASADOR', 'estado' => '1'],
            ['id' => '53', 'titulo' => 'TRADUCTOR', 'estado' => '1']
        ]);

        DB::table('expense_types')->insert([
            ['id' => '1', 'titulo' => 'DERECHOS NOTARIALES', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'DERECHOS REGISTRALES', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'DERECHOS MUNICIPALES', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'DERECHOS RENIEC', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'TASAS JUDICIALES ', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'COPIAS', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'MOVILIDAD', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'PUBLICACIONES ', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'VISUALIZACIONES ', 'estado' => '1'],
            ['id' => '10', 'titulo' => 'PAGO A TERCEROS', 'estado' => '1'],
            ['id' => '11', 'titulo' => 'DERECHOS POLICIALES', 'estado' => '1'],
            ['id' => '12', 'titulo' => 'COURIER', 'estado' => '1'],
            ['id' => '13', 'titulo' => 'ENVIO A PROVINCIA ', 'estado' => '1'],
            ['id' => '14', 'titulo' => 'SAT', 'estado' => '1'],
            ['id' => '15', 'titulo' => 'IMPUESTO VEHICULAR', 'estado' => '1'],
            ['id' => '16', 'titulo' => 'ENVIO AL EXTRANJERO', 'estado' => '1'],
            ['id' => '17', 'titulo' => 'IMPUESTO PREDIAL', 'estado' => '1'],
            ['id' => '18', 'titulo' => 'ARBITRIOS ', 'estado' => '1'],
            ['id' => '19', 'titulo' => 'IMPUESTO A LA RENTA ', 'estado' => '1'],
            ['id' => '20', 'titulo' => 'MULTAS', 'estado' => '1'],
            ['id' => '21', 'titulo' => 'COMISION BANCARIA', 'estado' => '1'],
            ['id' => '22', 'titulo' => 'BUSQUEDA Y UBICACION', 'estado' => '1']
        ]);

        DB::table('paises')->insert([
            ['id' => '1', 'titulo' => 'AFGANISTAN', 'estado' => '0'],
            ['id' => '2', 'titulo' => 'ALBANIA', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'ALEMANIA', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'ANDORRA', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'ANGOLA', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'ANGUILLA', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'ANTIGUA Y BARBUDA', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'ANTILLAS HOLANDESAS', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'ARABIA SAUDI', 'estado' => '1'],
            ['id' => '10', 'titulo' => 'ARGELIA', 'estado' => '1'],
            ['id' => '11', 'titulo' => 'ARGENTINA', 'estado' => '1'],
            ['id' => '12', 'titulo' => 'ARMENIA', 'estado' => '1'],
            ['id' => '13', 'titulo' => 'ARUBA', 'estado' => '1'],
            ['id' => '14', 'titulo' => 'AUSTRALIA', 'estado' => '1'],
            ['id' => '15', 'titulo' => 'AUSTRIA', 'estado' => '1'],
            ['id' => '16', 'titulo' => 'AZERBAIYAN', 'estado' => '1'],
            ['id' => '17', 'titulo' => 'BAHAMAS', 'estado' => '1'],
            ['id' => '18', 'titulo' => 'BAHREIN', 'estado' => '1'],
            ['id' => '19', 'titulo' => 'BANGLADESH', 'estado' => '1'],
            ['id' => '20', 'titulo' => 'BARBADOS', 'estado' => '1'],
            ['id' => '21', 'titulo' => 'BELARUS', 'estado' => '1'],
            ['id' => '22', 'titulo' => 'BELGICA', 'estado' => '1'],
            ['id' => '23', 'titulo' => 'BELICE', 'estado' => '1'],
            ['id' => '24', 'titulo' => 'BENIN', 'estado' => '1'],
            ['id' => '25', 'titulo' => 'BERMUDAS', 'estado' => '1'],
            ['id' => '26', 'titulo' => 'BHUTÁN', 'estado' => '1'],
            ['id' => '27', 'titulo' => 'BOLIVIA', 'estado' => '1'],
            ['id' => '28', 'titulo' => 'BOSNIA Y HERZEGOVINA', 'estado' => '1'],
            ['id' => '29', 'titulo' => 'BOTSWANA', 'estado' => '1'],
            ['id' => '30', 'titulo' => 'BRASIL', 'estado' => '1'],
            ['id' => '31', 'titulo' => 'BRUNEI', 'estado' => '1'],
            ['id' => '32', 'titulo' => 'BULGARIA', 'estado' => '1'],
            ['id' => '33', 'titulo' => 'BURKINA FASO', 'estado' => '1'],
            ['id' => '34', 'titulo' => 'BURUNDI', 'estado' => '1'],
            ['id' => '35', 'titulo' => 'CABO VERDE', 'estado' => '1'],
            ['id' => '36', 'titulo' => 'CAMBOYA', 'estado' => '1'],
            ['id' => '37', 'titulo' => 'CAMERUN', 'estado' => '1'],
            ['id' => '38', 'titulo' => 'CANADA', 'estado' => '1'],
            ['id' => '39', 'titulo' => 'CHAD', 'estado' => '1'],
            ['id' => '40', 'titulo' => 'CHILE', 'estado' => '1'],
            ['id' => '41', 'titulo' => 'CHINA', 'estado' => '1'],
            ['id' => '42', 'titulo' => 'CHIPRE', 'estado' => '1'],
            ['id' => '43', 'titulo' => 'COLOMBIA', 'estado' => '1'],
            ['id' => '44', 'titulo' => 'COMORES', 'estado' => '1'],
            ['id' => '45', 'titulo' => 'CONGO', 'estado' => '1'],
            ['id' => '46', 'titulo' => 'COREA', 'estado' => '1'],
            ['id' => '47', 'titulo' => 'COREA DEL NORTE ', 'estado' => '1'],
            ['id' => '48', 'titulo' => 'COSTA DE MARFIL', 'estado' => '1'],
            ['id' => '49', 'titulo' => 'COSTA RICA', 'estado' => '1'],
            ['id' => '50', 'titulo' => 'CROACIA', 'estado' => '1'],
            ['id' => '51', 'titulo' => 'CUBA', 'estado' => '1'],
            ['id' => '52', 'titulo' => 'DINAMARCA', 'estado' => '1'],
            ['id' => '53', 'titulo' => 'DJIBOUTI', 'estado' => '1'],
            ['id' => '54', 'titulo' => 'DOMINICA', 'estado' => '1'],
            ['id' => '55', 'titulo' => 'ECUADOR', 'estado' => '1'],
            ['id' => '56', 'titulo' => 'EGIPTO', 'estado' => '1'],
            ['id' => '57', 'titulo' => 'EL SALVADOR', 'estado' => '1'],
            ['id' => '58', 'titulo' => 'EMIRATOS ARABES UNIDOS', 'estado' => '1'],
            ['id' => '59', 'titulo' => 'ERITREA', 'estado' => '1'],
            ['id' => '60', 'titulo' => 'ESLOVENIA', 'estado' => '1'],
            ['id' => '61', 'titulo' => 'ESPAÑA', 'estado' => '1'],
            ['id' => '62', 'titulo' => 'ESTADOS UNIDOS DE AMERICA', 'estado' => '1'],
            ['id' => '63', 'titulo' => 'ESTONIA', 'estado' => '1'],
            ['id' => '64', 'titulo' => 'ETIOPIA', 'estado' => '1'],
            ['id' => '65', 'titulo' => 'FIJI', 'estado' => '1'],
            ['id' => '66', 'titulo' => 'FILIPINAS', 'estado' => '1'],
            ['id' => '67', 'titulo' => 'FINLANDIA', 'estado' => '1'],
            ['id' => '68', 'titulo' => 'FRANCIA', 'estado' => '1'],
            ['id' => '69', 'titulo' => 'GABON', 'estado' => '1'],
            ['id' => '70', 'titulo' => 'GAMBIA', 'estado' => '1'],
            ['id' => '71', 'titulo' => 'GEORGIA', 'estado' => '1'],
            ['id' => '72', 'titulo' => 'GHANA', 'estado' => '1'],
            ['id' => '73', 'titulo' => 'GIBRALTAR', 'estado' => '1'],
            ['id' => '74', 'titulo' => 'GRANADA', 'estado' => '1'],
            ['id' => '75', 'titulo' => 'GRECIA', 'estado' => '1'],
            ['id' => '76', 'titulo' => 'GROENLANDIA', 'estado' => '1'],
            ['id' => '77', 'titulo' => 'GUADALUPE', 'estado' => '1'],
            ['id' => '78', 'titulo' => 'GUAM', 'estado' => '1'],
            ['id' => '79', 'titulo' => 'GUATEMALA', 'estado' => '1'],
            ['id' => '80', 'titulo' => 'GUAYANA FRANCESA', 'estado' => '1'],
            ['id' => '81', 'titulo' => 'GUERNESEY', 'estado' => '1'],
            ['id' => '82', 'titulo' => 'GUINEA', 'estado' => '1'],
            ['id' => '83', 'titulo' => 'GUINEA ECUATORIAL', 'estado' => '1'],
            ['id' => '84', 'titulo' => 'GUINEA-BISSAU', 'estado' => '1'],
            ['id' => '85', 'titulo' => 'GUYANA', 'estado' => '1'],
            ['id' => '86', 'titulo' => 'HAITI', 'estado' => '1'],
            ['id' => '87', 'titulo' => 'HONDURAS', 'estado' => '1'],
            ['id' => '88', 'titulo' => 'HONG KONG', 'estado' => '1'],
            ['id' => '89', 'titulo' => 'HUNGRIA', 'estado' => '1'],
            ['id' => '90', 'titulo' => 'INDIA', 'estado' => '1'],
            ['id' => '91', 'titulo' => 'INDONESIA', 'estado' => '1'],
            ['id' => '92', 'titulo' => 'IRAN', 'estado' => '1'],
            ['id' => '93', 'titulo' => 'IRAQ', 'estado' => '1'],
            ['id' => '94', 'titulo' => 'IRLANDA', 'estado' => '1'],
            ['id' => '95', 'titulo' => 'ISLA DE MAN', 'estado' => '1'],
            ['id' => '96', 'titulo' => 'ISLA NORFOLK', 'estado' => '1'],
            ['id' => '97', 'titulo' => 'ISLANDIA', 'estado' => '1'],
            ['id' => '98', 'titulo' => 'ISLAS ALAND', 'estado' => '1'],
            ['id' => '99', 'titulo' => 'ISLAS CAIMÁN', 'estado' => '1'],
            ['id' => '100', 'titulo' => 'ISLAS COOK', 'estado' => '1'],
            ['id' => '101', 'titulo' => 'ISLAS DEL CANAL', 'estado' => '1'],
            ['id' => '102', 'titulo' => 'ISLAS FEROE', 'estado' => '1'],
            ['id' => '103', 'titulo' => 'ISLAS MALVINAS', 'estado' => '1'],
            ['id' => '104', 'titulo' => 'ISLAS MARIANAS DEL NORTE', 'estado' => '1'],
            ['id' => '105', 'titulo' => 'ISLAS MARSHALL', 'estado' => '1'],
            ['id' => '106', 'titulo' => 'ISLAS PITCAIRN', 'estado' => '1'],
            ['id' => '107', 'titulo' => 'ISLAS SALOMON', 'estado' => '1'],
            ['id' => '108', 'titulo' => 'ISLAS TURCAS Y CAICOS', 'estado' => '1'],
            ['id' => '109', 'titulo' => 'ISLAS VIRGENES BRITANICAS', 'estado' => '1'],
            ['id' => '110', 'titulo' => 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS', 'estado' => '1'],
            ['id' => '111', 'titulo' => 'ISRAEL', 'estado' => '1'],
            ['id' => '112', 'titulo' => 'ITALIA', 'estado' => '1'],
            ['id' => '113', 'titulo' => 'JAMAICA', 'estado' => '1'],
            ['id' => '114', 'titulo' => 'JAPON', 'estado' => '1'],
            ['id' => '115', 'titulo' => 'JERSEY', 'estado' => '1'],
            ['id' => '116', 'titulo' => 'JORDANIA', 'estado' => '1'],
            ['id' => '117', 'titulo' => 'KAZAJSTAN', 'estado' => '1'],
            ['id' => '118', 'titulo' => 'KENIA', 'estado' => '1'],
            ['id' => '119', 'titulo' => 'KIRGUISTAN', 'estado' => '1'],
            ['id' => '120', 'titulo' => 'KIRIBATI', 'estado' => '1'],
            ['id' => '121', 'titulo' => 'KUWAIT', 'estado' => '1'],
            ['id' => '122', 'titulo' => 'LAOS', 'estado' => '1'],
            ['id' => '123', 'titulo' => 'LESOTHO', 'estado' => '1'],
            ['id' => '124', 'titulo' => 'LETONIA', 'estado' => '1'],
            ['id' => '125', 'titulo' => 'LIBANO', 'estado' => '1'],
            ['id' => '126', 'titulo' => 'LIBERIA', 'estado' => '1'],
            ['id' => '127', 'titulo' => 'LIBIA', 'estado' => '1'],
            ['id' => '128', 'titulo' => 'LIECHTENSTEIN', 'estado' => '1'],
            ['id' => '129', 'titulo' => 'LITUANIA', 'estado' => '1'],
            ['id' => '130', 'titulo' => 'LUXEMBURGO', 'estado' => '1'],
            ['id' => '131', 'titulo' => 'MACAO', 'estado' => '1'],
            ['id' => '132', 'titulo' => 'MACEDONIA ', 'estado' => '1'],
            ['id' => '133', 'titulo' => 'MADAGASCAR', 'estado' => '1'],
            ['id' => '134', 'titulo' => 'MALASIA', 'estado' => '1'],
            ['id' => '135', 'titulo' => 'MALAWI', 'estado' => '1'],
            ['id' => '136', 'titulo' => 'MALDIVAS', 'estado' => '1'],
            ['id' => '137', 'titulo' => 'MALI', 'estado' => '1'],
            ['id' => '138', 'titulo' => 'MALTA', 'estado' => '1'],
            ['id' => '139', 'titulo' => 'MARRUECOS', 'estado' => '1'],
            ['id' => '140', 'titulo' => 'MARTINICA', 'estado' => '1'],
            ['id' => '141', 'titulo' => 'MAURICIO', 'estado' => '1'],
            ['id' => '142', 'titulo' => 'MAURITANIA', 'estado' => '1'],
            ['id' => '143', 'titulo' => 'MAYOTTE', 'estado' => '1'],
            ['id' => '144', 'titulo' => 'MEXICO', 'estado' => '1'],
            ['id' => '145', 'titulo' => 'MICRONESIA', 'estado' => '1'],
            ['id' => '146', 'titulo' => 'MOLDAVIA', 'estado' => '1'],
            ['id' => '147', 'titulo' => 'MONACO', 'estado' => '1'],
            ['id' => '148', 'titulo' => 'MONGOLIA', 'estado' => '1'],
            ['id' => '149', 'titulo' => 'MONTENEGRO', 'estado' => '1'],
            ['id' => '150', 'titulo' => 'MONTSERRAT', 'estado' => '1'],
            ['id' => '151', 'titulo' => 'MOZAMBIQUE', 'estado' => '1'],
            ['id' => '152', 'titulo' => 'MYANMAR', 'estado' => '1'],
            ['id' => '153', 'titulo' => 'NAMIBIA', 'estado' => '1'],
            ['id' => '154', 'titulo' => 'NAURU', 'estado' => '1'],
            ['id' => '155', 'titulo' => 'NEPAL', 'estado' => '1'],
            ['id' => '156', 'titulo' => 'NICARAGUA', 'estado' => '1'],
            ['id' => '157', 'titulo' => 'NIGER', 'estado' => '1'],
            ['id' => '158', 'titulo' => 'NIGERIA', 'estado' => '1'],
            ['id' => '159', 'titulo' => 'NIUE', 'estado' => '1'],
            ['id' => '160', 'titulo' => 'NORUEGA', 'estado' => '1'],
            ['id' => '161', 'titulo' => 'NUEVA CALEDONIA', 'estado' => '1'],
            ['id' => '162', 'titulo' => 'NUEVA ZELANDA', 'estado' => '1'],
            ['id' => '163', 'titulo' => 'OMAN', 'estado' => '1'],
            ['id' => '164', 'titulo' => 'PAISES BAJOS', 'estado' => '1'],
            ['id' => '165', 'titulo' => 'PAKISTAN', 'estado' => '1'],
            ['id' => '166', 'titulo' => 'PALAOS', 'estado' => '1'],
            ['id' => '167', 'titulo' => 'PALESTINA', 'estado' => '1'],
            ['id' => '168', 'titulo' => 'PANAMA', 'estado' => '1'],
            ['id' => '169', 'titulo' => 'PAPUA NUEVA GUINEA', 'estado' => '1'],
            ['id' => '170', 'titulo' => 'PARAGUAY', 'estado' => '1'],
            ['id' => '171', 'titulo' => 'PERÚ', 'estado' => '1'],
            ['id' => '172', 'titulo' => 'POLINESIA FRANCESA', 'estado' => '1'],
            ['id' => '173', 'titulo' => 'POLONIA', 'estado' => '1'],
            ['id' => '174', 'titulo' => 'PORTUGAL', 'estado' => '1'],
            ['id' => '175', 'titulo' => 'PUERTO RICO', 'estado' => '1'],
            ['id' => '176', 'titulo' => 'QATAR', 'estado' => '1'],
            ['id' => '177', 'titulo' => 'REINO UNIDO', 'estado' => '1'],
            ['id' => '178', 'titulo' => 'REP.DEMOCRATICA DEL CONGO', 'estado' => '1'],
            ['id' => '179', 'titulo' => 'REPUBLICA CENTROAFRICANA', 'estado' => '1'],
            ['id' => '180', 'titulo' => 'REPUBLICA CHECA', 'estado' => '1'],
            ['id' => '181', 'titulo' => 'REPUBLICA DOMINICANA', 'estado' => '1'],
            ['id' => '182', 'titulo' => 'REPUBLICA ESLOVACA', 'estado' => '0'],
            ['id' => '183', 'titulo' => 'REUNION', 'estado' => '1'],
            ['id' => '184', 'titulo' => 'RUANDA', 'estado' => '1'],
            ['id' => '185', 'titulo' => 'RUMANIA', 'estado' => '1'],
            ['id' => '186', 'titulo' => 'RUSIA', 'estado' => '1'],
            ['id' => '187', 'titulo' => 'SAHARA OCCIDENTAL', 'estado' => '1'],
            ['id' => '188', 'titulo' => 'SAMOA', 'estado' => '1'],
            ['id' => '189', 'titulo' => 'SAMOA AMERICANA', 'estado' => '1'],
            ['id' => '190', 'titulo' => 'SAN BARTOLOME', 'estado' => '1'],
            ['id' => '191', 'titulo' => 'SAN CRISTOBAL Y NIEVES', 'estado' => '1'],
            ['id' => '192', 'titulo' => 'SAN MARINO', 'estado' => '1'],
            ['id' => '193', 'titulo' => 'SAN MARTIN', 'estado' => '1'],
            ['id' => '194', 'titulo' => 'SAN PEDRO Y MIQUELON ', 'estado' => '1'],
            ['id' => '195', 'titulo' => 'SAN VICENTE Y LAS GRANADINAS', 'estado' => '1'],
            ['id' => '196', 'titulo' => 'SANTA HELENA', 'estado' => '1'],
            ['id' => '197', 'titulo' => 'SANTA LUCIA', 'estado' => '1'],
            ['id' => '198', 'titulo' => 'SANTA SEDE', 'estado' => '1'],
            ['id' => '199', 'titulo' => 'SANTO TOME Y PRINCIPE', 'estado' => '1'],
            ['id' => '200', 'titulo' => 'SENEGAL', 'estado' => '1'],
            ['id' => '201', 'titulo' => 'SERBIA', 'estado' => '1'],
            ['id' => '202', 'titulo' => 'SEYCHELLES', 'estado' => '1'],
            ['id' => '203', 'titulo' => 'SIERRA LEONA', 'estado' => '1'],
            ['id' => '204', 'titulo' => 'SINGAPUR', 'estado' => '1'],
            ['id' => '205', 'titulo' => 'SIRIA', 'estado' => '1'],
            ['id' => '206', 'titulo' => 'SOMALIA', 'estado' => '1'],
            ['id' => '207', 'titulo' => 'SRI LANKA', 'estado' => '1'],
            ['id' => '208', 'titulo' => 'SUDAFRICA', 'estado' => '1'],
            ['id' => '209', 'titulo' => 'SUDAN', 'estado' => '1'],
            ['id' => '210', 'titulo' => 'SUECIA', 'estado' => '1'],
            ['id' => '211', 'titulo' => 'SUIZA', 'estado' => '1'],
            ['id' => '212', 'titulo' => 'SURINAM', 'estado' => '1'],
            ['id' => '213', 'titulo' => 'SVALBARD Y JAN MAYEN', 'estado' => '1'],
            ['id' => '214', 'titulo' => 'SWAZILANDIA', 'estado' => '1'],
            ['id' => '215', 'titulo' => 'TADYIKISTAN', 'estado' => '1'],
            ['id' => '216', 'titulo' => 'TAILANDIA', 'estado' => '1'],
            ['id' => '217', 'titulo' => 'TANZANIA', 'estado' => '1'],
            ['id' => '218', 'titulo' => 'TIMOR ORIENTAL', 'estado' => '1'],
            ['id' => '219', 'titulo' => 'TOGO', 'estado' => '1'],
            ['id' => '220', 'titulo' => 'TOKELAU', 'estado' => '1'],
            ['id' => '221', 'titulo' => 'TONGA', 'estado' => '1'],
            ['id' => '222', 'titulo' => 'TRINIDAD Y TOBAGO', 'estado' => '1'],
            ['id' => '223', 'titulo' => 'TUNEZ', 'estado' => '1'],
            ['id' => '224', 'titulo' => 'TURKMENISTAN', 'estado' => '1'],
            ['id' => '225', 'titulo' => 'TURQUIA', 'estado' => '1'],
            ['id' => '226', 'titulo' => 'TUVALU', 'estado' => '1'],
            ['id' => '227', 'titulo' => 'UCRANIA', 'estado' => '1'],
            ['id' => '228', 'titulo' => 'UGANDA', 'estado' => '1'],
            ['id' => '229', 'titulo' => 'URUGUAY', 'estado' => '1'],
            ['id' => '230', 'titulo' => 'UZBEKISTAN', 'estado' => '1'],
            ['id' => '231', 'titulo' => 'VANUATU', 'estado' => '1'],
            ['id' => '232', 'titulo' => 'VENEZUELA', 'estado' => '1'],
            ['id' => '233', 'titulo' => 'VIETNAM', 'estado' => '1'],
            ['id' => '234', 'titulo' => 'WALLIS Y FORTUNA', 'estado' => '1'],
            ['id' => '235', 'titulo' => 'YEMEN', 'estado' => '1'],
            ['id' => '236', 'titulo' => 'ZAMBIA', 'estado' => '1'],
            ['id' => '237', 'titulo' => 'ZIMBABWE', 'estado' => '1']
        ]);

        DB::table('distritos')->insert([
            ['titulo' => 'Ancón', 'estado' => '1' ],
            ['titulo' => 'Santa Rosa', 'estado' => '1' ],
            ['titulo' => 'Ventanilla', 'estado' => '1' ],
            ['titulo' => 'Callao', 'estado' => '1' ],
            ['titulo' => 'La Punta', 'estado' => '1' ],
            ['titulo' => 'Carmen de La Legua-Reynoso', 'estado' => '1' ],
            ['titulo' => 'Bellavista', 'estado' => '1' ],
            ['titulo' => 'La Perla', 'estado' => '1' ],
            ['titulo' => 'Carabayllo', 'estado' => '1' ],
            ['titulo' => 'Puente Piedra', 'estado' => '1' ],
            ['titulo' => 'San Martín de Porres', 'estado' => '1' ],
            ['titulo' => 'Los Olivos', 'estado' => '1' ],
            ['titulo' => 'Comas', 'estado' => '1' ],
            ['titulo' => 'Independencia', 'estado' => '1' ],
            ['titulo' => 'San Juan de Lurigancho', 'estado' => '1' ],
            ['titulo' => 'Lima', 'estado' => '1' ],
            ['titulo' => 'Breña', 'estado' => '1' ],
            ['titulo' => 'Rímac', 'estado' => '1' ],
            ['titulo' => 'El Agustino', 'estado' => '1' ],
            ['titulo' => 'San Miguel', 'estado' => '1' ],
            ['titulo' => 'Pueblo Libre', 'estado' => '1' ],
            ['titulo' => 'Jesús María', 'estado' => '1' ],
            ['titulo' => 'Magdalena del Mar', 'estado' => '1' ],
            ['titulo' => 'Lince', 'estado' => '1' ],
            ['titulo' => 'La Victoria', 'estado' => '1' ],
            ['titulo' => 'San Luis', 'estado' => '1' ],
            ['titulo' => 'San Isidro', 'estado' => '1' ],
            ['titulo' => 'Miraflores', 'estado' => '1' ],
            ['titulo' => 'Surquillo', 'estado' => '1' ],
            ['titulo' => 'Barranco', 'estado' => '1' ],
            ['titulo' => 'San Borja', 'estado' => '1' ],
            ['titulo' => 'Santiago de Surco', 'estado' => '1' ],
            ['titulo' => 'Chorrillos', 'estado' => '1' ],
            ['titulo' => 'Santa Anita', 'estado' => '1' ],
            ['titulo' => 'Ate', 'estado' => '1' ],
            ['titulo' => 'La Molina', 'estado' => '1' ],
            ['titulo' => 'Lurigancho-Chosica', 'estado' => '1' ],
            ['titulo' => 'Chaclacayo', 'estado' => '1' ],
            ['titulo' => 'Cieneguilla', 'estado' => '1' ],
            ['titulo' => 'Pachacámac', 'estado' => '1' ],
            ['titulo' => 'San Juan de Miraflores', 'estado' => '1' ],
            ['titulo' => 'Villa María del Triunfo', 'estado' => '1' ],
            ['titulo' => 'Villa El Salvador', 'estado' => '1' ],
            ['titulo' => 'Lurín', 'estado' => '1' ],
            ['titulo' => 'Punta Hermosa', 'estado' => '1' ],
            ['titulo' => 'Punta Negra', 'estado' => '1' ],
            ['titulo' => 'San Bartolo', 'estado' => '1' ],
            ['titulo' => 'Santa María del Mar', 'estado' => '1' ],
            ['titulo' => 'Pucusana', 'estado' => '1' ]
        ]);

        DB::table('expediente_tipos')->insert([
            ['id' => '1', 'titulo' => 'CORPORATIVO / INMOBILIARIO / PERSONAS NATURALES / SUCESIONES', 'abrev' => 'C', 'num' => '5563', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'PROTESTOS', 'abrev' => 'H', 'num' => '726', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'PROCESAL', 'abrev' => 'J', 'num' => '317', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'VEHICULAR', 'abrev' => 'V', 'num' => '3931', 'estado' => '1']
        ]);
        
        DB::table('bienes')->insert([
            ['id' => '1', 'titulo' => 'Mueble', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'Inmueble', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'Vehículo', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'Varios', 'estado' => '1']
        ]);
        
        DB::table('situacion_especial')->insert([
            ['id' => '1', 'titulo' => 'Hipoteca', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'Embargo', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'Garantía', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'Otros', 'estado' => '1']
        ]);

        DB::table('exito')->insert([
            ['id' => '1', 'titulo' => 'Si', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'No', 'estado' => '1']
        ]);
        
        DB::table('tarea_conceptos')->insert([
            ['id' => '1', 'titulo' => 'BOLETA INFORMATIVA', 'estado' => '1'],
            ['id' => '2', 'titulo' => 'CANCELACION DE PAPELETA', 'estado' => '1'],
            ['id' => '3', 'titulo' => 'ENVIAR PAGARE A NOTARIA', 'estado' => '1'],
            ['id' => '4', 'titulo' => 'ESCANEAR DOCUMENTOS', 'estado' => '1'],
            ['id' => '5', 'titulo' => 'ESTADO DE CUENTA', 'estado' => '1'],
            ['id' => '6', 'titulo' => 'GRAVAMEN', 'estado' => '1'],
            ['id' => '7', 'titulo' => 'TRAMITE EN NOTARIA', 'estado' => '1'],
            ['id' => '8', 'titulo' => 'LEVANTAMIENTO DE GARANTIA MOBILIARIA', 'estado' => '1'],
            ['id' => '9', 'titulo' => 'PRESENTE ESCRITO AL PODER JUDICIAL', 'estado' => '1'],
            ['id' => '10', 'titulo' => 'RECOGER PAGARE DEL BANCO', 'estado' => '1'],
            ['id' => '11', 'titulo' => 'SACAR COPIA', 'estado' => '1'],
            ['id' => '12', 'titulo' => 'SEGUIMIENTO', 'estado' => '1'],
            ['id' => '13', 'titulo' => 'SOLICITAR DOCUMENTOS', 'estado' => '1'],
            ['id' => '14', 'titulo' => 'VISITA', 'estado' => '1'],
            ['id' => '15', 'titulo' => 'OTROS', 'estado' => '1']
        ]);
    }
}
